version: '3.8'

services:
  # Servicio de base de datos PostgreSQL
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: pymeai
      POSTGRES_PASSWORD: pymeaidev
      POSTGRES_DB: pymeai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de backend (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://pymeai:pymeaidev@db:5432/pymeai
      - SECRET_KEY=temporalsecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  # Servicio de frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:  # Volumen para persistir datos de PostgreSQL
