"""add interactions table

Revision ID: 54049639ff6a
Revises: d192fa225972
Create Date: 2025-08-12 22:25:31.904620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54049639ff6a'
down_revision = 'd192fa225972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###