"""add active sessions table

Revision ID: 6d9149cbf75d
Revises: 24ee7020daa9
Create Date: 2025-08-05 23:59:16.513925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9149cbf75d'
down_revision = '24ee7020daa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_sessions_id'), 'active_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_active_sessions_token'), 'active_sessions', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_active_sessions_token'), table_name='active_sessions')
    op.drop_index(op.f('ix_active_sessions_id'), table_name='active_sessions')
    op.drop_table('active_sessions')
    # ### end Alembic commands ###