"""add segment_definition table and customer segmentation fields

Revision ID: 897f71fb35ef
Revises: c0a2b18b5dda
Create Date: 2025-08-12 22:51:14.594661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897f71fb35ef'
down_revision = 'c0a2b18b5dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###