"""add customer segmentation fields

Revision ID: c0a2b18b5dda
Revises: 54049639ff6a
Create Date: 2025-08-12 22:39:36.300014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a2b18b5dda'
down_revision = '54049639ff6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('first_purchase_date', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('last_purchase_date', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('purchase_count', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('total_spent', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('average_purchase_value', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('purchase_frequency_days', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('days_since_last_purchase', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('segment_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'segment_updated_at')
    op.drop_column('customers', 'days_since_last_purchase')
    op.drop_column('customers', 'purchase_frequency_days')
    op.drop_column('customers', 'average_purchase_value')
    op.drop_column('customers', 'total_spent')
    op.drop_column('customers', 'purchase_count')
    op.drop_column('customers', 'last_purchase_date')
    op.drop_column('customers', 'first_purchase_date')
    # ### end Alembic commands ###