"""add dashboard models

Revision ID: cda8ecb06192
Revises: a3e7595c543c
Create Date: 2025-08-13 00:42:25.414219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda8ecb06192'
down_revision = 'a3e7595c543c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('display_type', sa.String(), nullable=False),
    sa.Column('target_value', sa.JSON(), nullable=True),
    sa.Column('warning_threshold', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpis_id'), 'kpis', ['id'], unique=False)
    op.create_table('dashboard_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_configs_id'), 'dashboard_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_configs_id'), table_name='dashboard_configs')
    op.drop_table('dashboard_configs')
    op.drop_index(op.f('ix_kpis_id'), table_name='kpis')
    op.drop_table('kpis')
    # ### end Alembic commands ###